const express=require('express')
const connectDB = require('./connectDB/connectDB')
const routerFashion = require('./routes/fashionRoutes')
const routerGraph = require('./routes/graphicRoutes')
const routerHand = require('./routes/handRoutes')
const routerProg = require('./routes/programmingRoutes')
const routerSport = require('./routes/sportRoutes')
const routerUp = require('./routes/uploadRoutes')
const routerUser = require('./routes/userRoutes')
const routerVid = require('./routes/videoRoutes')
require('dotenv').config()
const app=express()
const port=process.env.port
app.use(express.json())
connectDB()
app.use('/',routerProg)
app.use('/',routerHand)
app.use('/',routerGraph)
app.use('/',routerVid)
app.use('/',routerSport)
app.use('/',routerFashion)
app.use('/',routerUser)
app.use('/',routerUp)
app.listen(port,console.log('server is running at port: '+port))