export const REGISTER="REGISTER"
export const LOGIN="LOGIN"
export const GET_CURRENT="GET_CURRENT"
export const LOGOUT="LOGOUT"
export const GET_USERS="GET_USERS"
export const DELETE_USER="DELETE_USER"